name:                stk-lang
version:             0.1.0.0
github:              "githubuser/stk-lang"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/stk-lang#readme>

dependencies:
- base >= 4.7 && < 4.12
- mtl >= 2.2.2
- containers >= 0.6.2.1
- HList >= 0.5.0.0
- template-haskell >= 2.17.0.0
- ghc-prim >= 0.7.0
- fixed-list >= 0.1.6
- megaparsec >= 9.0.0
- syb >= 0.7.2.1
- haskell-src-exts >= 1.23.1
- haskell-src-meta >= 0.8.7

library:
  source-dirs: src

executables:
  stk-lang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stk-lang

tests:
  stk-lang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stk-lang
